### ISSUE TITLE
Pic in readme not shown

### ISSUE THREAD

**Issue by andimik** [glokhoff/RaspDAB#2]
Please upload the pic to github and link it there as this is not shown

![Photo of a RaspDAB setup](https://lh3.googleusercontent.com/xwmsbN_9FZEk_8zasF-dzpAjSGXvDYWWQvw34nfMGpAJHi8_OwQ1OORnRLHqSGrEjtT1nHSEqyPH9IA=w1304-h697)

> Invalid upstream response (403)

**Comment by glokhoff** [comment]
Thanks, I finally figured out how to correct this ;o)
