### ISSUE TITLE
Error when running ./raspdab.sh

### ISSUE THREAD

**Issue by jhansen1** [glokhoff/RaspDAB#4]
Hi. I get the following error when trying to run your script.

`jhansen@DABserver2:~ $ ./raspdab.sh
./raspdab.sh: line 7: syntax error near unexpected token `newline'
./raspdab.sh: line 7: `<!DOCTYPE html>'
`

**Comment by rmens** [comment]
You must have downloaded it wrong. There isn't a single line of html in the script. Maybe you downloaded the Github project page?

**Comment by jhansen1** [comment]
Ofcourse.. :)
