### ISSUE TITLE
Odr audio enc  

### ISSUE THREAD

**Issue by freedab** [glokhoff/RaspDAB#7]
Hi I really need help if you can  when I go to launch odr-audioenc I get an error saying ....while loading shared libraries libfdk-acc.so.1 cannot open shares object file no such file or directory .

**Comment by glokhoff** [comment]
Can you try to re-install odr-audioenc according to the installation instructions on the github page for ODR-AudioEnc ? The requirements may change with new versions or new linux release. Otherwise, please post your question in the mmbtools group on Google Groups.
