### ISSUE TITLE
Error compiling etisnoop

### ISSUE THREAD

**Issue by yorkie98** [glokhoff/RaspDAB#8]
Hi,
I get the following returned when the script is at the stage of compiling etisnoop.
Any help greatly appreciated.

 CXX	src/ensembledatabase.o
src/ensembledatabase.cpp:31:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
		               ^
compilation terminated.
Makefile647: recipe for target 'src/ensembledatabase.o' failed
make[1]: *** [src/ensembledatabase.o] Error 1
make[1[: Leaving directory 'home/dab/dab/etisnoop'
Makefile:318: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MetalMeyhemRadio** [comment]
Has this been answered? Having the same issue

**Comment by glokhoff** [comment]
I advise to follow the individual installation instructions for the various odr packages. Development continues and changes are likely in the installation requirements, as well as new linux releases. I don't have the time to follow all of these and adapt the script. ALso, when you install the packages manually this will take more time but you'll gain a better understanding of the structure.
